# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 07:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateYourLaws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyl_user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
