# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 11:35
from __future__ import unicode_literals

import CreateYourLaws.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateYourLaws', '0002_auto_20161027_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclaim',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=models.SET(CreateYourLaws.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='explaination',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=models.SET(CreateYourLaws.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lawarticle',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=models.SET(CreateYourLaws.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=models.SET(CreateYourLaws.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=models.SET(CreateYourLaws.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=models.SET(CreateYourLaws.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
