# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 11:30
from __future__ import unicode_literals

import CreateYourLaws.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('CreateYourLaws', '0005_auto_20170417_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negopinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('approval_factor', models.FloatField(default=0)),
                ('approval_ratio', models.FloatField(default=0)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('text_opn', ckeditor.fields.RichTextField()),
                ('nb_exp', models.IntegerField(default=0)),
                ('nb_q', models.IntegerField(default=0)),
                ('nb_dis', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(null=True, on_delete=models.SET(CreateYourLaws.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-approval_factor', '-update'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Posopinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('approval_factor', models.FloatField(default=0)),
                ('approval_ratio', models.FloatField(default=0)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('text_opp', ckeditor.fields.RichTextField()),
                ('nb_exp', models.IntegerField(default=0)),
                ('nb_q', models.IntegerField(default=0)),
                ('nb_dis', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(null=True, on_delete=models.SET(CreateYourLaws.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-approval_factor', '-update'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Opinion',
        ),
    ]
