# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateYourLaws', '0007_auto_20171119_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='text_prop',
            new_name='text_prp',
        ),
    ]
