# Generated by Django 2.0 on 2017-12-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateYourLaws', '0009_auto_20171220_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawprop',
            old_name='details',
            new_name='details_lwp',
        ),
        migrations.RenameField(
            model_name='proposition',
            old_name='details',
            new_name='details_prp',
        ),
    ]
