# Generated by Django 2.0 on 2018-02-11 18:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateYourLaws', '0010_auto_20171222_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawprop',
            name='lawarticle_ptr',
        ),
        migrations.AddField(
            model_name='lawarticle',
            name='details_law',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='lawarticle',
            name='is_lwp',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LawProp',
        ),
    ]
