# Generated by Django 2.0 on 2018-02-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateYourLaws', '0011_auto_20180211_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeblock',
            name='is_cdp',
            field=models.BooleanField(default=False),
        ),
    ]
