# Generated by Django 2.0 on 2018-02-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateYourLaws', '0012_codeblock_is_cdp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeblock',
            old_name='is_cdp',
            new_name='is_cbp',
        ),
    ]
