# Generated by Django 2.0.2 on 2018-03-07 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('CreateYourLaws', '0013_auto_20180226_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='cyl_user',
            name='is_punished',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cyl_user',
            name='nb_report',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
