# Generated by Django 2.0 on 2018-03-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateYourLaws', '0014_auto_20180307_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cyl_user',
            old_name='nb_report',
            new_name='report_level',
        ),
        migrations.AddField(
            model_name='disclaim',
            name='report_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='explaination',
            name='report_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lawarticle',
            name='report_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='negopinion',
            name='report_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posopinion',
            name='report_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposition',
            name='report_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='report_level',
            field=models.IntegerField(default=0),
        ),
    ]
