# Generated by Django 2.0 on 2018-03-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateYourLaws', '0016_commit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='commit',
            new_name='commit_details',
        ),
        migrations.AddField(
            model_name='commit',
            name='commit_title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='commit_txt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
